"""
Formats ExtractionResult into a tech.md-compatible markdown document
that the spec-validation agent can consume for test generation.

Output format matches the structure expected by test-generation-patterns.md:
- API endpoints with paths, methods, request/response types
- Type definitions (DTOs, entities) with fields
- Service interfaces with method signatures
"""

from .core import Endpoint, ExtractionResult, Parameter, ServiceMethod, TypeDefinition


def format_tech_md(result: ExtractionResult, project_name: str = "Project") -> str:
    sections = []
    sections.append(f"# {project_name} — Extracted API Surface\n")
    sections.append("**Generated by**: tree-sitter API surface extractor")
    sections.append("**Source**: Static analysis of codebase (deterministic, exhaustive)\n")
    sections.append("---\n")

    if result.endpoints:
        sections.append(_format_endpoints(result.endpoints))

    if result.types:
        sections.append(_format_types(result.types))

    if result.service_methods:
        sections.append(_format_services(result.service_methods))

    if result.errors:
        sections.append(_format_errors(result.errors))

    return "\n".join(sections)


def format_yaml(result: ExtractionResult) -> str:
    """Format as structured YAML for programmatic consumption."""
    import yaml

    data = {
        "endpoints": [_endpoint_to_dict(e) for e in result.endpoints],
        "types": [_type_to_dict(t) for t in result.types],
        "service_methods": [_service_method_to_dict(m) for m in result.service_methods],
    }
    return yaml.dump(data, default_flow_style=False, sort_keys=False)


def _format_endpoints(endpoints: list[Endpoint]) -> str:
    lines = ["## API Endpoints\n"]

    # Group by base path
    grouped: dict[str, list[Endpoint]] = {}
    for ep in endpoints:
        base = ep.path.split("/")[1] if "/" in ep.path else "root"
        grouped.setdefault(base, []).append(ep)

    for group_name, group_endpoints in sorted(grouped.items()):
        lines.append(f"### {group_name}\n")

        for ep in sorted(group_endpoints, key=lambda e: (e.path, e.http_method)):
            lines.append(f"#### {ep.http_method} `{ep.path}`\n")
            lines.append(f"**Handler**: `{ep.handler_name}`  ")
            lines.append(f"**File**: `{ep.file_path}:{ep.line_number}`\n")

            if ep.auth_required:
                roles_str = ", ".join(ep.roles) if ep.roles else "authenticated"
                lines.append(f"**Auth**: {roles_str}\n")

            if ep.parameters:
                lines.append("**Parameters**:\n")
                lines.append("| Name | Type | Source | Required |")
                lines.append("|------|------|--------|----------|")
                for p in ep.parameters:
                    lines.append(f"| {p.name} | `{p.type}` | {p.source} | {'yes' if p.required else 'no'} |")
                lines.append("")

            if ep.request_body_type:
                lines.append(f"**Request Body**: `{ep.request_body_type}`\n")

            if ep.return_type:
                lines.append(f"**Return Type**: `{ep.return_type}`\n")

            lines.append("---\n")

    return "\n".join(lines)


def _format_types(types: list[TypeDefinition]) -> str:
    lines = ["## Type Definitions\n"]

    # Separate by kind
    dtos = [t for t in types if _is_dto(t)]
    entities = [t for t in types if _is_entity(t)]
    others = [t for t in types if not _is_dto(t) and not _is_entity(t)]

    if dtos:
        lines.append("### Request/Response Types (DTOs)\n")
        for t in sorted(dtos, key=lambda x: x.name):
            lines.extend(_format_single_type(t))

    if entities:
        lines.append("### Entities/Models\n")
        for t in sorted(entities, key=lambda x: x.name):
            lines.extend(_format_single_type(t))

    if others:
        lines.append("### Other Types\n")
        for t in sorted(others, key=lambda x: x.name):
            lines.extend(_format_single_type(t))

    return "\n".join(lines)


def _format_single_type(t: TypeDefinition) -> list[str]:
    lines = []
    parent_str = f" extends {', '.join(t.parent_types)}" if t.parent_types else ""
    lines.append(f"#### `{t.name}`{parent_str}\n")
    lines.append(f"**Kind**: {t.kind}  ")
    lines.append(f"**File**: `{t.file_path}:{t.line_number}`\n")

    if t.annotations:
        lines.append(f"**Annotations**: {', '.join(t.annotations[:5])}\n")

    if t.fields:
        lines.append("| Field | Type | Required |")
        lines.append("|-------|------|----------|")
        for f in t.fields:
            lines.append(f"| {f.name} | `{f.type}` | {'yes' if f.required else 'no'} |")
        lines.append("")

    return lines


def _format_services(methods: list[ServiceMethod]) -> str:
    lines = ["## Service Interfaces\n"]

    # Group by interface name
    grouped: dict[str, list[ServiceMethod]] = {}
    for m in methods:
        key = m.interface_name or "standalone"
        grouped.setdefault(key, []).append(m)

    for iface_name, iface_methods in sorted(grouped.items()):
        lines.append(f"### {iface_name}\n")
        lines.append(f"**File**: `{iface_methods[0].file_path}`\n")

        for m in iface_methods:
            params_str = ", ".join(f"{p.name}: {p.type}" for p in m.parameters)
            return_str = f" → {m.return_type}" if m.return_type else ""
            lines.append(f"- `{m.name}({params_str}){return_str}` (line {m.line_number})")

        lines.append("")

    return "\n".join(lines)


def _format_errors(errors: list[str]) -> str:
    lines = ["## Extraction Warnings\n"]
    lines.append("The following files had parsing issues:\n")
    for error in errors[:20]:
        lines.append(f"- {error}")
    if len(errors) > 20:
        lines.append(f"\n... and {len(errors) - 20} more")
    return "\n".join(lines)


def _is_dto(t: TypeDefinition) -> bool:
    name_lower = t.name.lower()
    return any(suffix in name_lower for suffix in
               ("request", "response", "dto", "schema", "input", "output", "payload"))


def _is_entity(t: TypeDefinition) -> bool:
    return any("@Entity" in a or "@Table" in a or "BaseModel" in a
               for a in t.annotations) or t.kind == "entity"


def _endpoint_to_dict(ep: Endpoint) -> dict:
    return {
        "method": ep.http_method,
        "path": ep.path,
        "handler": ep.handler_name,
        "file": f"{ep.file_path}:{ep.line_number}",
        "parameters": [_param_to_dict(p) for p in ep.parameters],
        "request_body_type": ep.request_body_type,
        "return_type": ep.return_type,
        "auth_required": ep.auth_required,
        "roles": ep.roles,
    }


def _type_to_dict(t: TypeDefinition) -> dict:
    return {
        "name": t.name,
        "kind": t.kind,
        "file": f"{t.file_path}:{t.line_number}",
        "fields": [_param_to_dict(f) for f in t.fields],
        "parent_types": t.parent_types,
    }


def _service_method_to_dict(m: ServiceMethod) -> dict:
    return {
        "name": m.name,
        "interface": m.interface_name,
        "file": f"{m.file_path}:{m.line_number}",
        "parameters": [_param_to_dict(p) for p in m.parameters],
        "return_type": m.return_type,
    }


def _param_to_dict(p: Parameter) -> dict:
    d = {"name": p.name, "type": p.type}
    if not p.required:
        d["required"] = False
    if p.source != "body":
        d["source"] = p.source
    if p.default:
        d["default"] = p.default
    return d
